### ISSUE TITLE
Tooltip persists in fixed position on mobile screen when inside "fixed" container

### ISSUE THREAD

**Issue by crobinson42** [bsidelinger912/react-tooltip-lite#58]
When the Tooltip is inside an element with css `position: fixed`, and on a mobile device, if the user taps the tooltip it will appear as expected. When the user scrolls inside the element with css `overflow: auto|scroll` the Tooltip will stay in a fixed position on the viewport.

I forked the example codepen and wrapped in a fixed container element to demonstrate. I tested this on iOS Chrome and Safari to demonstrate the bug.

https://codepen.io/coryrobinson42/pen/NWKzBRK

**Comment by bsidelinger912** [comment]
Thanks for the pen @crobinson42! I'll dig in further this weekend.

**Comment by crobinson42** [comment]
Thanks and please let me know if I can help this is a big issue for my app right now.

**Comment by bsidelinger912** [comment]
@crobinson42 I think that this is fixed by v1.11 because scrolling should dismiss existing tips and new ones shouldn't be opened when the tap was part of a scroll gesture.  Let me know if this fixes the issue you're seeing.

**Comment by crobinson42** [comment]
@bsidelinger912 this is still an issue in the latest release 1.11. Steps to reproduce in my app is for a user on mobile to dragpressstart on the screen over text that is wrapped with the tooltip, scroll/drag some direction and when dragpressstop (finger release) the tooltip will appear at the x/y coordinates where the dragpressstart event was initialized.

**Comment by bsidelinger912** [comment]
Interesting, I wasn't seeing the tip open if a scroll occurred between when you tapped and released.  I'll check again with your pen now that the new version is available from s3.

**Comment by bsidelinger912** [comment]
I think this will end up being the same fix as the remaining issue on https://github.com/bsidelinger912/react-tooltip-lite/issues/59

**Comment by bsidelinger912** [comment]
@crobinson42, I believe this is now addressed with v1.11.2.  The fixes I proved on 1.11.0 for ignoring taps when scrolling didn't work for internal scrollbars such as within fixed position divs, 1.11.2 finds the nearest scrollable ancestor and listens for scrolls on that to either ignore taps, or recalculate tip position.  Please let me know when you have a chance to check it out.

**Comment by crobinson42** [comment]
This is fixed @bsidelinger912
