### ISSUE TITLE
Tooltips don't disappear on mobile when scrolling

### ISSUE THREAD

**Issue by scf4** [bsidelinger912/react-tooltip-lite#59]
If I accidentally trigger tooltips while scrolling on mobile, they don't disappear when you tap outside of them, as expected. 

Any ideas for how to solve this? The hover delay is ignored on mobile, so they're really easy to trigger.

**Comment by crobinson42** [comment]
@scf4 is this at all related to #58 ? Have you checked if there are any parent container elements that have position `absolute` or `fixed`?

**Comment by scf4** [comment]
> @scf4 is this at all related to #58 ? Have you checked if there are any parent container elements that have position `absolute` or `fixed`?

Can’t check right now but I think it’s unrelated. No parent containers have position set!

**Comment by snowinmars** [comment]
> @scf4 is this at all related to #58 ? Have you checked if there are any parent container elements that have position `absolute` or `fixed`?

For sure: position of the `body` element is absolute.
The code: https://stackblitz.com/edit/react-2dsnov
Click 'share' > 'app url' and open it. You should see something like [this](https://yadi.sk/i/fuaxzhgzKOc1-Q)

What is the best way to fix this issue?

**Comment by bsidelinger912** [comment]
Hey guys, I've been away for a couple weeks on my honeymoon and am just getting back to this stuff.  I'll be thinking more about this this weekend, thanks for your patience.

**Comment by crobinson42** [comment]
Congrats!! 🍾🎉

**Comment by MukiA** [comment]
Congratulations! I'm also having issues with this, both on mobile and computer but especially on mobile  where the tooltips are triggered on tap-scrolling and refuse to go away when you scoll past them. Multiple tooltips can also be active at the same time on mobile and refuse to go away unless you click on them. In some cases a tap to disable the tooltip actually triggers the tooltip to appear one more time which results in 2 taps just to close it down. Would be great if you manage to solve this :)

**Comment by bsidelinger912** [comment]
I believe this is addressed with v1.11

**Comment by crobinson42** [comment]
This is still a problem with new release 1.11. I am using iOS 13 Chrome browser.

**Comment by bsidelinger912** [comment]
Hey @crobinson42, I was able to reproduce this easily before I made the fix, at least the issue I could understand.  It's a little hard to tell exactly what issue you're seeing.  I've added a tap handler so that if you tap outside the tip it closes.  I'm pretty sure that's fixed now, and that is is original issue reported here.  It may that other issues came up that relate though.  Are you seeing that the tips don't disappear when you tap outside of them?

**Comment by crobinson42** [comment]
@bsidelinger912 I do see the tooltips disappear when you tap outside of them.

The problem that still persists is that if a scroll (mobile) is started over an element that is wrapped with the tooltip then the tooltip will appear  in that position as soon as the finger "fling" (scroll fling up or down) is released. Does that make sense?

**Comment by crobinson42** [comment]
Also, for what it's worth I only have a fixed container app wrapper that has `overflow: scroll` so I don't know if this is an issue if the body is scrolling..

**Comment by bsidelinger912** [comment]
Aaaah, thanks @crobinson42 I know what's happening now.  I'll start working on this.

**Comment by bsidelinger912** [comment]
@crobinson42 I believe this is now fixed for both the OP's scenario and your scenario for internal scrollbars, in v1.11.2 please let me know when you have a chance to check it out.

**Comment by crobinson42** [comment]
The issue that still exists is when the tooltip repositions and the child element has been scrolled out of screen the tooltip will stick to the top/bottom of the screen. This happens on large lists
